/*
Post Format JS
Copyright (c) BetterGaia and Bowafishtech
Unauthorized copying, sharing, adaptation, publishing, commercial usage, and/or distribution, its derivatives and/or successors, via any medium, is strictly prohibited.
*/
function Format(){function f(d,b){for(var a=[];a.length<b;)a.push(d);return a.join("")}!0===prefs.format&&(-1<document.location.pathname.indexOf("/forum/")&&!0===prefs["format.forums"]||-1<document.location.pathname.indexOf("/guilds/posting.php")&&!0===prefs["format.guildForums"]||-1<document.location.pathname.indexOf("/profile/privmsg.php")&&!0===prefs["format.pms"]||-1<document.location.search.indexOf("mode=addcomment")&&!0===prefs["format.profileComments"])&&($('textarea[name="message"]:not([identity]), textarea[name="comment"]:not([identity])').each(function(){var d=
    Date.now(),b=$(this);$(this).add("select[name=basic_type]:not([identity])").attr("identity",d);var a="";"object"==typeof localPrefs["format.list"]&&$.isEmptyObject(prefs["format.list"])&&(prefs["format.list"]=localPrefs["format.list"],console.warn("Your formats are currently saved locally."));var e=!1;if("default"!=prefs["format.list.recent"]&&!0===prefs["format.list.useRecent"])for(var g=0;g<prefs["format.list"].length;g++)if(prefs["format.list"][g][0]==prefs["format.list.recent"]){e=!0;break}$.each(prefs["format.list"],
    function(g,c){if(0===g&&!e||e&&c[0]==prefs["format.list.recent"]){a+='<a code="'+c[1]+'" poststyle="'+c[2]+'" class="current">'+c[0]+"</a>";if('[quote="'==b.val().substr(0,8)&&"[/quote]"==b.val().replace(/\n\s*/g,"").substr(-8)){!0===prefs["format.quote.removeFormatting"]&&b.val(b.val().replace(/\[\/?(?:b|i|u|strike|code|url|color|size|align|img|imgleft|imgright|imgmap|youtube|spoiler).*?\]/img,""));if(!0===prefs["format.quote.spoilerWrap"]){var h=b.val().slice(0,-8),h=(h+"[/spoiler][/quote]").replace(/\[quote=(.+?)\]/,
    "[quote=$1][spoiler]");b.val(h)}!0===prefs["format.quote.endOfFormat"]?b.val(decodeURI(c[1])+"\n"+f("\n",parseInt(prefs["format.quote.rangeNumber"],10))+b.val()):b.val(b.val()+"\n"+f("\n",parseInt(prefs["format.quote.rangeNumber"],10))+decodeURI(c[1]))}else 0===b.val().length&&b.val(decodeURI(c[1]));$('select[name=basic_type][identity="'+d+'"]').val(c[2])}else a+='<a code="'+c[1]+'" poststyle="'+c[2]+'">'+c[0]+"</a>"});$(this).after('<div id="bg_formatter" identity="'+d+'">'+a+"</div>")}),$("#bg_formatter > a").on("click",
    function(){if(!$(this).hasClass("current")){var d=decodeURI($(this).attr("code")),b=$(this).parent().attr("identity"),a=$('textarea[identity="'+b+'"]');if(encodeURI(a.val())==$(this).siblings("a.current").attr("code"))a.val(d);else{if(-1!=encodeURI(a.val()).indexOf($(this).siblings("a.current").attr("code"))){var e=encodeURI(a.val()).replace($(this).siblings("a.current").attr("code"),""),e=e.replace("%0A"+f("%0A",parseInt(prefs["format.quote.rangeNumber"],10)),"");a.val(decodeURI(e))}!0===prefs["format.quote.endOfFormat"]?
    a.val(d+"\n"+f("\n",parseInt(prefs["format.quote.rangeNumber"],10))+a.val()):a.val(a.val()+"\n"+f("\n",parseInt(prefs["format.quote.rangeNumber"],10))+d)}$('select[name=basic_type][identity="'+b+'"]').val($(this).attr("poststyle"));$(this).siblings("a.current").removeClass("current");$(this).addClass("current");0!==$(this).index()?(chrome.storage.sync.set({"format.list.recent":$(this).text()}),prefs["format.list.recent"]=$(this).text()):(chrome.storage.sync.remove("format.list.recent"),prefs["format.list.recent"]=
    "default")}return!1}))}!0===prefs.appliedUserPrefs&&!1===prefs.appliedFormat&&(Format(),prefs.appliedFormat=!0);
