/*
Forum JS
Copyright (c) BetterGaia and Bowafishtech
Unauthorized copying, sharing, adaptation, publishing, commercial usage, and/or distribution, its derivatives and/or successors, via any medium, is strictly prohibited.
*/
function ForumJs(){if(!0===prefs.announcementReader&&"/news/"==document.location.pathname&&1==$("#gaia_header #notifyItemList .notify_announcements .notify_icon_announcement").length){var d=parseInt($("#gaia_header #notifyItemList .notify_announcements .notify_icon_announcement").text().replace(/\D/g,""),10);10<d&&(d=10);var e=1==d?"":"s";$("#content").prepend('<a id="bgFetchAnnouncements">You still have '+d+" announcement"+e+" to open. Would you like to open the rest on this page?</a>");$("#bgFetchAnnouncements").on("click",
function(){function a(){console.log("apply");$.ajax({url:"/news/",cache:!1,dataType:"html",headers:{"X-PJAX":!0}}).done(function(b){if(1==$("#thread_header #thread_title",b).length){var c=1==d?", Newest":"";$("#bgFetchAnnouncements").after('<h3 class="bgFAh3">'+d+c+'</h3><div id="content-padding">'+b+"</div>")}else d=0;console.log(d);0<d?(d--,a()):($("#gaia_header #notifyItemList .notify_announcements, #bgFetchAnnouncements").remove(),ForumJs())})}$("#bgFetchAnnouncements").after('<h3 class="bgFAh3">'+
(d+1)+", Oldest</h3>");$(this).off("click").addClass("loading").text("Fetching your announcements...");a()})}!0===prefs["forum.previewThreads"]&&($("body.forums #gaia_content table.forum-list tr td.title .one-line-title .topic-icon").after('<a class="bgThreadPreview" title="View the first post of this thread">[+]</a>'),$("body.forums #gaia_content table.forum-list tr td.title .one-line-title a.bgThreadPreview").on("click",function(){if(0===$(this).closest("tr.rowon, tr.rowoff").next("tr.bgThreadPreviewBox").length){$(this).closest("tr.rowon, tr.rowoff").after('<tr class="bgThreadPreviewBox loading"><td colspan="6"><div>Test</div></td></tr>');
var a=$(this).closest("tr.rowon, tr.rowoff").next("tr.bgThreadPreviewBox");$.ajax({type:"GET",url:$(this).siblings("a[href]:not(.goto-new-posts)").attr("href"),headers:{"X-PJAX":!0},success:function(b){b=$("<div>").html(b);var c=b.find("#post-1 .avi_box").html();b=b.find("#post-1 .post-bubble").html();a.removeClass("loading").find("td > div").html("<div class='bgavi'>"+c+"</div><div class='bgbubble'>"+b+"</div>")},error:function(b){a.html("There was a problem retrieving the post.").removeClass("loading")}})}else $(this).closest("tr.rowon, tr.rowoff").next("tr.bgThreadPreviewBox").find("td > div").slideToggle("slow")}));
$("body.forums #content #content-padding #topic_header_container .detail-navlinks .thread_options").append('<div class="bg_postoptions"><a class="bgpo_toggle bgpo_posts"><on>Hide</on><off>Show</off> Posts</a> <a class="bgpo_toggle bgpo_sigs"><on>Hide</on><off>Show</off> Sigs</a></div>');"boolean"==typeof localPrefs["forum.hidePosts"]&&!0===localPrefs["forum.hidePosts"]&&($("body.forums #content #content-padding #topic_header_container .detail-navlinks .thread_options .bg_postoptions .bgpo_posts, body.forums #content #content-padding #topic_header_container .detail-navlinks .thread_options .bg_postoptions .bgpo_sigs").addClass("bgpo_on"),
$("body.forums #post_container .post .post-signature").hide(),$("body.forums #post_container .post").addClass("bgpc_hidden"));$("body.forums #topic_header_container .detail-navlinks .thread_options .bg_postoptions .bgpo_posts").on("click",function(){$(this).hasClass("bgpo_on")?($("body.forums #content #content-padding #topic_header_container .detail-navlinks .thread_options .bg_postoptions .bgpo_posts").removeClass("bgpo_on"),$("body.forums #content #content-padding #topic_header_container .detail-navlinks .thread_options .bg_postoptions .bgpo_posts").parent().parent().find(".bgpo_sigs").removeClass("bgpo_on"),
$("body.forums #post_container .post .post-signature").show(),$("body.forums #post_container .post").removeClass("bgpc_hidden"),chrome.storage.local.remove("forum.hidePosts",function(){delete localPrefs["forum.hidePosts"]})):($("body.forums #content #content-padding #topic_header_container .detail-navlinks .thread_options .bg_postoptions .bgpo_posts").addClass("bgpo_on"),$("body.forums #content #content-padding #topic_header_container .detail-navlinks .thread_options .bg_postoptions .bgpo_posts").parent().parent().find(".bgpo_sigs").addClass("bgpo_on"),
$("body.forums #post_container .post .post-signature").hide(),$("body.forums #post_container .post").addClass("bgpc_hidden"),chrome.storage.local.set({"forum.hidePosts":!0},function(){localPrefs["forum.hidePosts"]=!0}))});$("body.forums #content #content-padding #topic_header_container .detail-navlinks .thread_options .bg_postoptions .bgpo_sigs").on("click",function(){$("body.forums #content #content-padding #topic_header_container .detail-navlinks .thread_options .bg_postoptions .bgpo_sigs").hasClass("bgpo_on")?
($("body.forums #content #content-padding #topic_header_container .detail-navlinks .thread_options .bg_postoptions .bgpo_sigs").removeClass("bgpo_on"),$("body.forums #post_container .post .post-signature").show()):($("body.forums #content #content-padding #topic_header_container .detail-navlinks .thread_options .bg_postoptions .bgpo_sigs").addClass("bgpo_on"),$("body.forums #post_container .post .post-signature").hide())});$("body.forums .post .post-signature").each(function(){$(this).parent().find(".message .messagecontent > .post-options > ul > li.post-meta").before('<li><a class="bg_togglesig"><span>Hide Sig</span></a></li>')});
$("body.forums .post .message .messagecontent a.bg_togglesig").click(function(){$(this).closest(".postcontent").find(".post-signature").toggle()});$("body.forums .post .user_info_wrapper .user_info").each(function(){0===$(this).find(".bg_postcollapse").length&&$(this).append('<div class="bg_postcollapse" title="Collapse/Expand Post"></div>')});$("body.forums .post .user_info_wrapper .user_info .bg_postcollapse").click(function(){$(this).closest(".post").toggleClass("bgpc_hidden")});$("body.forums .post .message .messagecontent .post-options ul").each(function(){(0<
    $(this).find("a.post-quote").length||0<$(this).find("a.post-edit").length)&&$(this).prepend('<div class="bg_instant"><li><a class="bg_instanttext"><span>Instant</span></a></li></div>');0<$(this).find("a.post-quote").length&&$(this).find(".bg_instant").append('<li><a class="bg_instantquote"><span>Quote</span></a></li>');0<$(this).find("a.post-edit").length&&$(this).find(".bg_instant").append('<li><a class="bg_instantedit"><span>Edit</span></a></li>')});$("body.forums .post .message .messagecontent .post-options ul a.bg_instantquote").click(function(){var a=
        $(this).closest(".messagecontent");if(0===a.find(".bg_instantbox.quote").length){a.find(".post-bubble").after("<div class='bg_instantbox quote loading'></div>");var b=a.find(".post-options a.post-quote").attr("href");$.get(b).done(function(c){c=$("<div>").html(c);c.find("script").remove();a.find(".bg_instantbox.quote").removeClass("loading").html(c.find("form#compose_entry")[0].outerHTML);"function"===typeof Format?Format():chrome.extension.sendMessage({elements:"format"})})}else $(this).closest(".messagecontent").find(".bg_instantbox.quote").slideToggle("slow")});
        $("body.forums .post .message .messagecontent .post-options ul a.bg_instantedit").click(function(){var a=$(this).closest(".messagecontent");if(0===a.find(".bg_instantbox.edit").length){a.find(".post-bubble").after("<div class='bg_instantbox edit loading'></div>");var b=a.find(".post-options a.post-edit").attr("href");$.get(b).done(function(c){c=$("<div>").html(c);c.find("script").remove();a.find(".bg_instantbox.edit").removeClass("loading").html(c.find("form#compose_entry")[0].outerHTML)})}else $(this).closest(".messagecontent").find(".bg_instantbox.edit").slideToggle("slow")});
        if(!0===prefs["forum.externalLinks"])$("body.forums .post a[href^='http://www.gaiaonline.com/gaia/redirect.php?r=']").on("click",function(a){if(1<$(this).prop("href").match(/gaiaonline/g).length||a.ctrlKey||2==a.which)return!0;$("body").append($("<div class='bgredirect'></div>"));var b=$(this).prop("href");$(this).children("img").attr("ismap")&&(b+="?"+a.offsetX+","+a.offsetY);$.ajax({type:"GET",url:b,dataType:"html",success:function(a){a=$("<div>").html(a);a.find("script").remove();$(".bgredirect").html($("<div>"+
            a.html()+"</div>").html());$(".bgredirect table.warn_block #warn_block #warn_head").append("<a class='bgclose' title='close'></a>");$(".bgredirect a").attr("target","_blank");$(".bgredirect a.link_display, .bgredirect a.bgclose").on("click",function(){$(".bgredirect").remove()})},error:function(){$(".bgredirect").remove();window.open(b)}});return!1});!0===prefs.usertags&&("object"==typeof localPrefs["usertags.list"]&&$.isEmptyObject(prefs["usertags.list"])&&(prefs["usertags.list"]=localPrefs["usertags.list"],
            console.warn("Your tags are currently saved locally.")),$("body.forums .post .user_info_wrapper .user_info .user_name").each(function(){if(0===$(this).siblings(".bgUserTag").length){var a="",a=$(this).closest(".postcontent").find(".avatar_wrapper .avi_box"),a=0===a.find("a.avatar").length?a.find("#animated_item > object").attr("onmousedown").replace("window.location='","").split("/")[5]:a.find("a.avatar").attr("href").split("/")[5];$(this).after('<div class="bgUserTag"><a target="_blank" title="Tag" userid="'+
            a+'"></a><span></span></div>')}}),e=prefs["usertags.list"],$('.bgUserTag a[userid="8152358"]').each(function(){1!=$(this).closest(".postcontent").find('.message .post-bubble span[style="color: #FEFEF0"] span[style="font-size: 1px"]').length&&$(this).attr({href:"/forum/t.45053993/"}).text("BetterGaia Creator")}),$.isEmptyObject(e)||$.each(e,function(a,b){if($('.bgUserTag a[userid="'+a+'"]')){var c=b[2];c.match(/\S/)&&1<c.length?$('.bgUserTag a[userid="'+a+'"]').attr({href:c}).text(b[1]):$('.bgUserTag a[userid="'+
            a+'"]').text(b[1])}}),$("body.forums .post .user_info_wrapper .user_info .bgUserTag > span").on("click",function(){if($(this).closest(".post").hasClass("bgut_loaded"))$(this).closest(".post").toggleClass("bgut_open");else{var a="",b=$(this).closest(".postcontent").find(".post-directlink a").attr("href");0<$(this).siblings("a").text().length&&(a=$(this).siblings("a").text(),$(this).siblings("a").attr("href")&&(b=$(this).siblings("a").attr("href")));$(this).after("<div><h2>Tag "+$(this).closest(".user_info").find(".user_name").text()+
            '<a class="bgclose"></a></h2><form><label for="bgut_tagtag">Tag</label><input type="text" id="bgut_tagtag" maxlength="50" placeholder="Notes and comments" value="'+a+'"><label for="bgut_idtag">User ID</label><input type="text" id="bgut_idtag" placeholder="Numerical" value="'+$(this).siblings("a").attr("userid")+'"><label for="bgut_linktag">Link</label><input type="text" id="bgut_linktag" placeholder="URL" value="'+b+'"><p>You can manage your tags in your BetterGaia Settings.</p><a class="bgut_save">Save</a></form></div>');
            $(this).closest(".post").addClass("bgut_loaded bgut_open")}$(this).parent().find("#bgut_tagtag").focus()}),$("body.forums .post .user_info_wrapper .user_info").on("click",".bgUserTag a.bgclose",function(){$(this).closest(".post").removeClass("bgut_open")}),$("body.forums .post .user_info_wrapper .user_info").on("click",".bgUserTag a.bgut_save",function(){var a=!1,b=$(this).closest(".user_info").find(".user_name").text(),c=$(this).siblings("#bgut_tagtag"),d=$(this).siblings("#bgut_idtag"),e=$(this).siblings("#bgut_linktag");
            !c.val().match(/\S/)||1>c.val().length?c.prev("label").addClass("bgerror"):$(this).siblings('label[for="bgut_tagtag"].bgerror').removeClass("bgerror");1>d.val().length||!d.val().match(/\S/)||!$.isNumeric(d.val())?d.prev("label").addClass("bgerror"):$(this).siblings('label[for="bgut_idtag"].bgerror').removeClass("bgerror");0===$(this).siblings(".bgerror").length&&(a=!0);a&&(prefs["usertags.list"][d.val()]=[b,c.val(),e.val(),Date.now()],chrome.storage.sync.set({"usertags.list":prefs["usertags.list"]},
            function(){function a(){$('body.forums .post .user_info_wrapper .user_info .bgUserTag a[userid="'+d.val()+'"]').attr({href:e.val()}).text(c.val());c.closest(".post").removeClass("bgut_loaded bgut_open");c.closest("div").remove()}"object"==typeof chrome.runtime.lastError?(console.warn("Error when setting tags: "+chrome.runtime.lastError.message),"QUOTA_BYTES_PER_ITEM quota exceeded"==chrome.runtime.lastError.message&&chrome.storage.local.set({"usertags.list":prefs["usertags.list"]},function(){console.log("tags saved locally.");
            chrome.storage.sync.set({"usertags.list":{}});a()})):(console.log("tags saved to sync."),chrome.storage.local.remove("usertags.list"),a())}))}));$("body.forums .post .message .messagecontent > .post-options > ul > li.post-meta").each(function(){$(this).appendTo($(this).closest(".postcontent").find(".user_info_wrapper .user_info"))})}!0===prefs.appliedUserPrefs&&!1===prefs.appliedForumJs&&(ForumJs(),prefs.appliedForumJs=!0);
            if(1==$("#topic_header_container #thread_header").length){var observer=new window.MutationObserver(function(d){ForumJs()});observer.observe(document.getElementById("content-padding"),{attributes:!1,childList:!0,characterData:!1})};
