/*
CSS JS
Copyright (c) BetterGaia and Bowafishtech
Unauthorized copying, sharing, adaptation, publishing, commercial usage, and/or distribution, its derivatives and/or successors, via any medium, is strictly prohibited.
*/
var link=document.createElement("link");link.href=chrome.extension.getURL("code/css/pure-min.css");link.type="text/css";link.rel="stylesheet";document.documentElement.appendChild(link);var link2=document.createElement("link");link2.href=chrome.extension.getURL("code/css/main.css");link2.type="text/css";link2.rel="stylesheet";document.documentElement.appendChild(link2);
function MainCss(){var a="";!1===prefs["header.float"]&&(a+="body #gaia_header #user_header_wrap > #user_account, body #gaia_header #bg_userbar {position: absolute;}");!1===prefs["mygaia.suggested"]&&(a+="body.mygaia #gaia_content #bd .mg_content.suggested {display: block;}");"default"!=prefs["background.image"]&&(a+="body.time-day, body.time-night, body.time-dawn, .time-dusk, body table.warn_block {background-image: url("+prefs["background.image"]+");}");"default"!=prefs["background.image"]&&(a=
    a+"body.time-day, body.time-night, body.time-dawn, .time-dusk, body table.warn_block {"+("background-color: "+prefs["background.color"]+";"),a+="background-position: "+prefs["background.position"]+";",a=!1===prefs["background.repeat"]?a+"background-repeat: no-repeat;":a+"background-repeat: repeat;",a=!0===prefs["background.float"]?a+"background-attachment: fixed;":a+"background-attachment: scroll;",a+="}");"http://s.cdn.gaiaonline.com/images/global_bg/bg2.jpg"==prefs["background.image"]&&(a+="body.time-day, body.time-night, body.time-dawn, .time-dusk, body table.warn_block {background-position: bottom left !important; background-repeat: no-repeat !important; background-color: #12403d !important;}");
    "default"!=prefs["header.background"]&&(a+=".time-day div.town-barton .header_content, .time-dawn div.town-barton .header_content, .time-dusk div.town-barton .header_content {background-image: url("+prefs["header.background"]+");}");"default"!=prefs["header.background.base"]&&(a+=".time-day div.town-barton, .time-dawn div.town-barton, .time-dusk div.town-barton {background: url("+prefs["header.background.base"]+") repeat-x;}");!1===prefs["header.background.stretch"]&&(a+="body div#gaia_header {width: 1140px;}");
    "default"!=prefs["header.logo"]&&(a+="body #gaia_header .header_content .gaiaLogo a, body #gaia_header .header_content .gaiaLogo a:hover {background-image: url("+prefs["header.logo"]+");}");var a=a+("body #gaia_header .hud-account > ul, body #gaia_menu_bar {background-color: "+prefs["header.nav"]+";}"),b;b=parseInt(prefs["header.nav.current"],16);b=(b>>16&255)+","+(b>>8&255)+","+(b&255);a+="body #gaia_header .header_content .goldMessage {linear-gradient(to right, rgba("+b+", 0), rgba("+b+",0.5), rgba("+
    b+",0)), radial-gradient(ellipse at center top, rgba(255,255,255,0.25), rgba(255,255,255,0) 50%), radial-gradient(ellipse at center bottom, rgba(0,0,0,0.25), rgba(0,0,0,0) 50%);}";a+="#nav > li:not(#menu_search):hover, #nav > li:not(#menu_search):hover:active {background-color: "+prefs["header.nav.hover"]+";}";a+="#nav > li.selected {background-color: "+prefs["header.nav.current"]+";}";b=document.createElement("style");b.type="text/css";b.setAttribute("bg-css","");b.appendChild(document.createTextNode(a));
    document.documentElement.appendChild(b);!0===prefs.instantUpdating&&"string"==typeof localPrefs.css&&(a=document.createElement("style"),a.type="text/css",a.setAttribute("bg-updatedcss",""),a.appendChild(document.createTextNode(localPrefs.css)),document.documentElement.appendChild(a))}
    !0!==prefs.appliedUserPrefs?chrome.storage.sync.get(null,function(a){chrome.storage.local.get(null,function(b){localPrefs=b;for(var c in a)try{prefs[c]=a[c]}catch(d){console.warn("BetterGaia: Missing pref '"+d+"'.")}prefs.appliedUserPrefs=!0;"function"==typeof MainCss&&!1===prefs.appliedMainCss&&(MainCss(),prefs.appliedMainCss=!0);"function"==typeof MainJs&&!1===prefs.appliedMainJs&&(MainJs(),prefs.appliedMainJs=!0);"function"==typeof ForumCss&&!1===prefs.appliedForumCss&&(ForumCss(),prefs.appliedForumCss=
    !0);"function"==typeof ForumJs&&!1===prefs.appliedForumJs&&(ForumJs(),prefs.appliedForumJs=!0);"function"==typeof Format&&!1===prefs.appliedFormat&&(Format(),prefs.appliedFormat=!0)})}):MainCss();
